// Generates src/version.ts from package.json's "version" so the runtime version (the
// `vk --version` banner and the plan-cache compiler fingerprint) stays in lockstep with
// the published version without hand-editing. Wired into the `prebuild` npm script.
// Idempotent: it only writes when the value changed, so a normal build leaves no git noise.
// Plain ESM, zero deps (matches scripts/github-test-summary.mjs).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const target = join(root, 'src', 'version.ts');

const contents = `// GENERATED by scripts/gen-version.mjs from package.json's "version" at build time
// (the \`prebuild\` script). Do NOT edit by hand; bump package.json instead.
export const VERSION = '${version}';
`;

const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
if (current !== contents) {
  writeFileSync(target, contents);
  console.error(`[gen-version] src/version.ts -> VERSION=${version}`);
}
